### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by spixy** [wireless-r/Light-Switch#1]
Hi, thank you for this app. Anyway after pressing `Save changes`, I got an error:

> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\spixy\AppData\Local\Temp\LightSwitch\Wallpapers'.
>    at System.IO.Enumeration.FileSystemEnumerator.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
>    at System.IO.Enumeration.FileSystemEnumerator.Init()
>    at System.IO.Enumeration.FileSystemEnumerator.ctor(String directory, Boolean isNormalized, EnumerationOptions options)
>    at System.IO.Enumeration.FileSystemEnumerable.ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
>    at System.IO.Enumeration.FileSystemEnumerableFactory.FileInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
>    at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
>    at System.IO.DirectoryInfo.GetFiles(String searchPattern, EnumerationOptions enumerationOptions)
>    at System.IO.DirectoryInfo.GetFiles()
>    at LightSwitch.Facades.FileFacade.ClearTemp(String subfolder, String[] exceptions) in C:\Users\Joakim Magnussen\OneDrive\Prosjekter\Light Switch\src\Light Switch\Light Switch\Facades\FileFacade.cs:line 55
>    at LightSwitch.Forms.PreferencesForm.btnSave_Click(Object sender, EventArgs e) in C:\Users\Joakim Magnussen\OneDrive\Prosjekter\Light Switch\src\Light Switch\Light Switch\Forms\PreferencesForm.cs:line 174
>    at System.Windows.Forms.Control.OnClick(EventArgs e)
>    at System.Windows.Forms.Button.OnClick(EventArgs e)
>    at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>    at System.Windows.Forms.Button.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

There are no `LightSwitch\Wallpapers` folders in my Temp. After creating them manually it now works.

**Comment by joakimmag** [comment]
Thanks for reporting this. I'll issue a fix.

**Comment by joakimmag** [comment]
This has been fixed.
