### ISSUE TITLE
Win7?? Also.. x86/64x .Net??

### ISSUE THREAD

**Issue by crogonint** [wireless-r/Light-Switch#2]
Sorry to throw two rocks in the pond at the same time..

1) MajorGeeks says this is for Win 7|8|10, but your blurb specifically says Win10. I should note that it LET me install it in Win7, so..?

2) It says that I have to install .Net core, and takes me to the .Net 3.1 page.. which wants to know if I want the x86 or 64x version.. When it installed, I noted that your program is x86, but my OS is Win7 64x.. So.. which .Net do I use?? I would assume x86, but that's not something that I want to assume.

Bonus rock) Why do I need .Net for a dinky little system 'app'? Seems like overkill, but what do I know?

**Comment by wireless-r** [comment]
Hi @crogonint. Thank you for writing.
I'm not affiliated with the website you mention and have nothing to do with its contents.
This application supplements the the light/dark mode feature which is only found in Windows 10. No other OS is supported.
It also requires the .NET Core 3.1 runtime or higher.
I'll close this one, but feel free to write if you have any questions.

**Comment by joakimmag** [comment]
Hi @crogonint. Thank you for posting an issue.
I'm not affiliated with the website you mention and have nothing to do with its contents.
This application takes advantage of the the light/dark mode feature which is found in Windows 10.
As such only Windows 10 is supported.
As for x64/x86, install the same as your system. 
I'll close this one, but feel free to write if you have any questions.

**Comment by crogonint** [comment]
Yeah.. Immediately after installing this in Win7, I got a permanent blue screen of death, due to display related issues, according to the error code. Is it possible that this corrupted the Win7 64x display, and can you think of any way to uninstall it from Win7 extrernally? I'm currently on a Linux desktop trying to make do.
