### ISSUE TITLE
Missing .NET Core

### ISSUE THREAD

**Issue by spixy** [wireless-r/Light-Switch#6]
Hi, on startup I got this error:
![image](https://user-images.githubusercontent.com/4542110/163671806-7cc2a183-5359-4eb2-aa36-940ed576f5bd.png)
and after clicking on yes I installed this:
![image](https://user-images.githubusercontent.com/4542110/163671822-9a290a0a-b170-4de1-9d30-17ac24a587fc.png)
but app still shows that dialog and wont start.
Also when do you plan to upgrade to .NET 5/6?

**Comment by joakimmag** [comment]
Hi, and thank you for opening an issue with Light Switch, your feedback is valuable. I am going to ask you some questions, can you please go to Properties for `C:\Program Files (x86)\Light Switch\Light Switch.exe` and write your Product Version?

![image](https://user-images.githubusercontent.com/28116634/163717072-210377d8-25c4-4202-8749-f6cbdb89e38b.png)

**Comment by spixy** [comment]
no it was 2.1, I updated to 2.2 and problem is gone, thanks
